### ISSUE TITLE
nb-select not rendering options in a stepper, when not in the first page

### ISSUE THREAD

**Issue by H-Theking** [akveo/nebular#1292]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

I have a stepper within a window that I use for a setup wizard. The first form has several nb-selects whose options are rendered. The third form also has an nb-select. However it's options aren' rendered. When the window opens, the backend call for the data needed by the third form is loaded, and I display it in the console but on reaching the third form, no options are available to select from.

I used an observable to have the data load only when the second form is successfully submitted. Works with a normal select but still not with ng-select. 

**Expected behavior:**

When the third form is loaded, the nb-select should have data bound to its options.

**Steps to reproduce:**

- Create a  component A, having a stepper.
- Create two components, B and C, each having a form an nb-selects.
- Include the forms in component A
- Have both forms call a service in the back end to get data.
- Display A in a window
- Start the application and have the window displayed
- Move to form B
-  Try to select and option from the dropdown

### Other information:

**npm, node, OS, Browser**
```
NPM v6.8.0
Angular CLI: 7.0.5
Node: 8.9.4
OS: Windows 8 win32 x64
Angular: 7.0.3
Browser: Chrome

```

**Nebular**
```
@nebular/auth": "3.1.0
@nebular/bootstrap": "3.1.0
@nebular/security": "3.1.0
@nebular/theme": "3.1.0

**Comment by elSuperRiton** [comment]
Same issue here. Interestingly the select will also stop working after moving back in the stepper. 
I can also confirm that it seems to be broken when used in tabs and accordion also :s

**Comment by nnixaa** [comment]
Fixed in https://github.com/akveo/nebular/pull/1316

**Comment by saidsoualhi** [comment]
this issue is not fixed yet.
in my case:
I have a nb-select in the header to change the theme, it works well for the first load, but after changing the route it's not working anymore the click on the nb-select don't show the options
( no error on the console )

https://user-images.githubusercontent.com/29822280/110376188-2ff29500-8053-11eb-8a48-348cfb540145.mp4

```
 "@nebular/auth": "^7.0.0",
  "@nebular/eva-icons": "^7.0.0",
  "@nebular/security": "^7.0.0",
  "@nebular/theme": "^7.0.0",
```

```
OS: Windows 10 win32 x64
Angular: 11.2.0
Browser: Chrome
```
