### ISSUE TITLE
Is it possible to open a dialog from a service?

### ISSUE THREAD

**Issue by ilDon** [akveo/nebular#879]
### Issue type

**I'm submitting a ...**

* [ ] bug report
* [X] feature request

### Issue description

**Current behavior:**

I would like to open a dialog from a service, is it possible?

**Expected behavior:**

Open a dialog from a Service

Currently if I try to do it I get this error: `Cannot read property 'appendChild' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'appendChild' of undefined`

**Comment by ilDon** [comment]
Hi @algirdasc, I'm not sure I understood your question.

What I'm trying to do is this:

Template

    <button (click)="doStuff()">Do something</button>

Component

    constructor(
      private myService: MyServiceService,
      private viewContainerRef: ViewContainerRef
    ){}
   
    doStuff(): void {
      this.myService.openDialog(this.viewContainerRef);
    }

MyServiceService

    export class MyServiceService {

      constructor(
        private dialogRef: NbDialogRef
      ) { }

      openDialog(viewContainerRef: ViewContainerRef): void {
         this.dialogService.open(MyDialogComponent, {
           viewContainerRef
         });
      }     

    }

I've also tried without passing `ViewContainerRef` from the component, and I've also tried to pass the dialogRef from the component, but I still get that error.

**Comment by algirdasc** [comment]
Sorry, what I meant was, did you wrapped your router-outlet in nb-layout? I had similiar problem, but solved by doing this in my template:
```
@Component({
    template: `<nb-layout>
        <nb-layout-column>
            <router-outlet></router-outlet>
        </nb-layout-column>
    </nb-layout>`
})
```

**Comment by faztp12** [comment]
I am also facing the same issue, and yes I have the router-outlet wrapped in nb-layout 😕

**Comment by faztp12** [comment]
![image](https://user-images.githubusercontent.com/12441615/47506735-5488b080-d88e-11e8-911b-ee3131830e89.png)
You could see that `NbOverlayContainerAdapter` was initialized twice, but only in one `setContainer()` of `NbOverlayContainerAdapter` was called, which causes this error.

The second instance gets made on navigating to a lazy loaded module. I tried following following the `.forRoot()` calls but can't find the culprit 😭 

If anybody has any more insights, please help out :)

**Comment by Tibing** [comment]
Hi @faztp12, could you please provide us a reproducible [stackblitz](http://stackblitz.com)?

**Comment by faztp12** [comment]
The issue #943 has a reproducible stackblitz, https://stackblitz.com/edit/nebular-overlay-container-adapter-bug :)

**Comment by eliseurm** [comment]
I'm also having the same problem. issue #943

Please, someone could sort out or tell you the correct way to use NbDialog.

**Comment by Tibing** [comment]
Hi All. The issue was resolved here: https://github.com/akveo/nebular/issues/943#issuecomment-436908742

**Comment by faztp12** [comment]
@Tibing 
I think this issue still persist. Wrapping <nb-layout> at component root fixed #943 
But, the issue still exists when we try to open a dialog from a service.

The issue i observed:
There are two components, A & B lazy loaded into same router outlet wrapped in an nb-layout

load A, everything works fine
load B, try to open a dialog (invoke function in service), nothing shows up
I have RouteReuseStrategy, and when i go back to A, i see the dialog meant to be shown at B visible 😃 
Weird I know

What I understand is, the service on invoking showDialog, does it on an nb-layout related to the lazy loaded component instead of the root app component ?

Is there anyway we could specify, hey service - use the root nb-layout for the dialogs ?

**Comment by faztp12** [comment]
Looks like Lazy loaded modules gets services instantiated twice.
I had a mechanism to have it loaded only once and that caused all the mayhem.

If people are facing this issue: console log in your service constructor and watch no. instantiation
Then, get it instantiated in root component, (simple injection) and this makes sure the dialog comes up in root component's context.

Nebular supports dialogs from services.
Also it shows it in nearest nb-layout found wrt the injected component

hope it helps
